### ISSUE TITLE
Colored tags + milestones - in the list of tickets and on detail

### ISSUE THREAD

**Issue by klokan** [klokantech/clientportal#19]
To make the presentation of issues a bit more userfriendly - and similar to GitHub.

**Comment by klokan** [comment]
This is very annoying as well - reported on Nov 19 2014.

**Comment by o1da** [comment]
Tags are colored, but I don't know what to do with milestones - can you specify it with more detail?

**Comment by klokan** [comment]
It is OK now. Thanks!
Some more love on CSS would be require in future - but that's for another ticket.
