### ISSUE TITLE
Linking the issues

### ISSUE THREAD

**Issue by klokan** [klokantech/clientportal#22]
In the text of tickets should be replaced links to github by links to clientportal.

Example:
http://clientportal.klokantech.com/georeferencer/issues/104/

is linking #49 in the same repo. This needs to go to:
http://clientportal.klokantech.com/georeferencer/issues/49/ instead to github.com.

**Comment by klokan** [comment]
This should be done - it is a trivial patch with search and replace. Please prioritise it!

**Comment by klokan** [comment]
Here is a wrong ticket link in a comment:
http://clientportal.klokantech.com/kartenportal/issues/300/

**Comment by o1da** [comment]
I will look on it after 'hawk' project deadline.
