### ISSUE TITLE
Images (or attachments) in reply missing

### ISSUE THREAD

**Issue by klokan** [klokantech/clientportal#24]
Attachments submitted by email and embedded images are completely unreachable.

See this email for example:
https://github.com/klokantech/iiifviewer/issues/7#issuecomment-74718032

Clientportal MUST replace the links with something meaningful.

Can you provide us with the links to images customer submitted above?

**Comment by klokan** [comment]
What is the status of this?

**Comment by o1da** [comment]
It is not finished yet, I'm going to finish it after 'hawk' project deadline.

**Comment by klokan** [comment]
Files to be saved in a random named directory (one per ticket) locally - with the original filenames.

Add also upload form for the clients (autheticated) to upload any file they want - storage will be the same way. Uploaded files are linked in comment.

**Comment by o1da** [comment]
It is done and deployed. I created /uploads/ folder in the clientportal folder and it is served by lighttypd directly everything else is sent to gunicorn.

Name of the subfolder is md5 hash from the project shortcut and issue number.
Simple upload form is done too.

**Comment by klokan** [comment]
Thanks! Clients will love it!

**Comment by klokan** [comment]
Hmm - no submit button on creating an issue :-(.

It should look like this:
![screen shot 2015-05-04 at 16 13 30](https://cloud.githubusercontent.com/assets/59284/7455029/2c54af28-f279-11e4-831e-97fbbe988cdd.png)

Also - this looks horribly. Ideally it should be like the mockup above (above the comment button).
If not possible, at least fix the padding. 
![screen shot 2015-05-04 at 16 13 01](https://cloud.githubusercontent.com/assets/59284/7454940/99211ae8-f278-11e4-999e-8473f5ee6052.png)

Please think about usability!

**Comment by o1da** [comment]
Done, I added multiple files upload too.

**Comment by klokan** [comment]
Perfect! Thank you a lot!
