### ISSUE TITLE
First email is not submitted to all labels

### ISSUE THREAD

**Issue by klokan** [klokantech/clientportal#26]
When two customers (two labels) as assigned automatically on a project - both these customers should receive an email when a ticket is created.

We have a report that this is not happening:

See: https://github.com/klokantech/kartenportal-tickets/issues/300

This must be fixed soon - and we need to let know the customer on the ticket above.

**Comment by o1da** [comment]
Done. There is a problem with order of issue creating and labeling. Sometimes information about label change is send from github before information about issue creation. And I mean it is really send before, not only received on the clientportal side (due of network). And if you have more labels, these situation with sending email only to some users not to all can happen. I done some tweaks before, but I have just realized that I had bug in it, So it is repaired now.
When I receive information about new issue, I don't trust labels sent with this information and request information about labels again. Emails are sent after.

**Comment by klokan** [comment]
Client portal is creating the issue and assigning the labels - so you have everything you need already in the moment when a user hits "Submit" on the form with the new ticket text.

Anyway - thanks for the fix.

**Comment by o1da** [comment]
Yes but if I do it immediately after submit I would have to filter it when
I will receive info about new issue from github webhook. I think that
solution without filtering is cleaner. And I even don't know how to filter
it if issue is made from github directly. It would be more difficult.

2015-04-09 19:40 GMT+02:00 Petr Pridal <notifications@github.com>:
