### ISSUE TITLE
Budget not visible in a newly added project

### ISSUE THREAD

**Issue by klokan** [klokantech/clientportal#27]
The hour budget was not loaded from Harvest it seems, neither the total nor the already used hours.

Project:
Kartenportal Maintenance 2015
http://clientportal.klokantech.com/project/16/
https://klokantech.harvestapp.com/projects/7521725

**Comment by o1da** [comment]
Reports are downloaded with external script which is run periodically via cron. So it can takes some time to download and show reports. I have just setted cron to do it once per hour.
