### ISSUE TITLE
Remove empty hamburger menu on public tickets

### ISSUE THREAD

**Issue by klokan** [klokantech/clientportal#38]
See: https://clientportal.klokantech.com/airbus/issues/90/

(this is submitted to Google engineers now)

It is unprofessional to have it there. Could you please fix it @o1da ?

**Comment by klokan** [comment]
Also - can we have the issues on URL without trailing / - and redirect on URL with slash to URL without slash - so both are served?

**Comment by o1da** [comment]
Empty hamburger menu is solved (will be deployed after actual refactoring of code). Issues works with URL with trailing / and without too on new version of Clientportal.
